# Generated by Django 3.2.16 on 2023-03-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_born', models.PositiveSmallIntegerField(default=0)),
                ('year_dead', models.PositiveSmallIntegerField(default=0)),
                ('history_life', models.TextField()),
                ('image', models.ImageField(upload_to='authors/')),
                ('url', models.SlugField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='books/')),
                ('year', models.PositiveSmallIntegerField(default=2000)),
                ('country', models.CharField(max_length=30)),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('directors', models.ManyToManyField(related_name='author', to='book_shop.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.SlugField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=5000)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book_shop.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='book_shop.Genre'),
        ),
    ]
