# Generated by Django 3.2.16 on 2023-03-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0003_rating_ratingstar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value']},
        ),
    ]
